name: Deploy to GitHub Packages

description: This GitHub Action deploys built artifacts to GitHub Packages registry.

runs:
  using: composite
  steps:
    - name: Checkout repos
      uses: actions/checkout@v4
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://npm.pkg.github.com/
        always-auth: true
    - name: Update npm
      shell: pwsh
      run: npm install -g npm
    - name: Update package.json
      shell: pwsh
      run: npm version ${{env.BUILD_VERSION}}-beta.${{github.run_number}} --no-git-tag-version
    - name: Restore source
      shell: pwsh
      run: npm ci
    - name: Audit source
      shell: pwsh
      run: npm audit --omit=dev
    - name: Build source
      shell: pwsh
      run: npm run build
    - name: Create .npmrc
      shell: pwsh
      run: |
        touch .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{env.GITHUB_TOKEN}}" >> .npmrc
        echo "@karamem0:registry=https://npm.pkg.github.com/" >> .npmrc
    - name: Publish source
      shell: pwsh
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{env.GITHUB_TOKEN}}
