name: Deploy to GitHub Release

description: This GitHub Action deploys built artifacts to GitHub Release.

runs:
  using: composite
  steps:
    - name: Create release
      uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
