on:
  push:
    branches:
      - main

permissions:
  packages: write
      
jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/publish-ghp.yml
    secrets: inherit
    with:
      environment: prd
