on: workflow_call

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Update package.json
        run: npm version ${{vars.BUILD_VERSION}} --no-git-tag-version
      - name: Restore source
        run: npm ci
      - name: Audit source
        run: npm audit --omit=dev
      - name: Build source
        run: npm run build
      - name: Publish source
        run: npm publish --provenance --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
