on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/publish-npm.yml
    secrets: inherit
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    secrets: inherit
