on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*.*.*

permissions:
  id-token: write
  packages: write

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/')
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - name: Update package.json
        run: npm version ${{vars.BUILD_VERSION}}-beta.${{github.run_number}} --no-git-tag-version
      - name: Restore source
        run: npm ci
      - name: Audit source
        run: npm audit --omit=dev
      - name: Build source
        run: npm run build
      - name: Create .npmrc
        run: |
          touch .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
          echo "@karamem0:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: Publish source
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish-npm:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Update package.json
        run: npm version ${{vars.BUILD_VERSION}} --no-git-tag-version
      - name: Restore source
        run: npm ci
      - name: Audit source
        run: npm audit --omit=dev
      - name: Build source
        run: npm run build
      - name: Publish source
        run: npm publish --provenance --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
